#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtimageformats
Version  : 5.11.1
Release  : 13
URL      : http://download.qt.io/official_releases/qt/5.11/5.11.1/submodules/qtimageformats-everywhere-src-5.11.1.tar.xz
Source0  : http://download.qt.io/official_releases/qt/5.11/5.11.1/submodules/qtimageformats-everywhere-src-5.11.1.tar.xz
Summary  : A library of functions for manipulating MNG format files.
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.3 GPL-2.0 GPL-3.0 JasPer-2.0 LGPL-2.1 LGPL-3.0 W3C libtiff
Requires: qtimageformats-lib
Requires: qtimageformats-license
BuildRequires : libwebp-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : python3-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-extras
BuildRequires : scons
BuildRequires : tiff-dev

%description
libmng - library for reading, writing, displaying and examing
Multiple-Image Network Graphics. MNG is the animation extension to the
popular PNG image-format.

%package dev
Summary: dev components for the qtimageformats package.
Group: Development
Requires: qtimageformats-lib
Provides: qtimageformats-devel

%description dev
dev components for the qtimageformats package.


%package lib
Summary: lib components for the qtimageformats package.
Group: Libraries
Requires: qtimageformats-license

%description lib
lib components for the qtimageformats package.


%package license
Summary: license components for the qtimageformats package.
Group: Default

%description license
license components for the qtimageformats package.


%prep
%setup -q -n qtimageformats-everywhere-src-5.11.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
%qmake
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1530943513
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/qtimageformats
cp LICENSE.GPLv3 %{buildroot}/usr/share/doc/qtimageformats/LICENSE.GPLv3
cp LICENSE.LGPLv3 %{buildroot}/usr/share/doc/qtimageformats/LICENSE.LGPLv3
cp LICENSE.GPL3 %{buildroot}/usr/share/doc/qtimageformats/LICENSE.GPL3
cp LICENSE.GPL3-EXCEPT %{buildroot}/usr/share/doc/qtimageformats/LICENSE.GPL3-EXCEPT
cp LICENSE.GPLv2 %{buildroot}/usr/share/doc/qtimageformats/LICENSE.GPLv2
cp LICENSE.GPL2 %{buildroot}/usr/share/doc/qtimageformats/LICENSE.GPL2
cp LICENSE.FDL %{buildroot}/usr/share/doc/qtimageformats/LICENSE.FDL
cp LICENSE.LGPLv21 %{buildroot}/usr/share/doc/qtimageformats/LICENSE.LGPLv21
cp LICENSE.LGPL3 %{buildroot}/usr/share/doc/qtimageformats/LICENSE.LGPL3
cp src/3rdparty/jasper/LICENSE %{buildroot}/usr/share/doc/qtimageformats/src_3rdparty_jasper_LICENSE
cp src/3rdparty/jasper/COPYRIGHT %{buildroot}/usr/share/doc/qtimageformats/src_3rdparty_jasper_COPYRIGHT
cp src/3rdparty/libtiff/COPYRIGHT %{buildroot}/usr/share/doc/qtimageformats/src_3rdparty_libtiff_COPYRIGHT
cp src/3rdparty/libwebp/COPYING %{buildroot}/usr/share/doc/qtimageformats/src_3rdparty_libwebp_COPYING
cp src/3rdparty/libmng/LICENSE %{buildroot}/usr/share/doc/qtimageformats/src_3rdparty_libmng_LICENSE
cp src/3rdparty/libmng/qt_LICENSE %{buildroot}/usr/share/doc/qtimageformats/src_3rdparty_libmng_qt_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/lib64/cmake/Qt5Gui/Qt5Gui_QICNSPlugin.cmake
/usr/lib64/cmake/Qt5Gui/Qt5Gui_QTgaPlugin.cmake
/usr/lib64/cmake/Qt5Gui/Qt5Gui_QTiffPlugin.cmake
/usr/lib64/cmake/Qt5Gui/Qt5Gui_QWbmpPlugin.cmake
/usr/lib64/cmake/Qt5Gui/Qt5Gui_QWebpPlugin.cmake

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/imageformats/libqicns.so
/usr/lib64/qt5/plugins/imageformats/libqtga.so
/usr/lib64/qt5/plugins/imageformats/libqtiff.so
/usr/lib64/qt5/plugins/imageformats/libqwbmp.so
/usr/lib64/qt5/plugins/imageformats/libqwebp.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/qtimageformats/LICENSE.FDL
/usr/share/doc/qtimageformats/LICENSE.GPL2
/usr/share/doc/qtimageformats/LICENSE.GPL3
/usr/share/doc/qtimageformats/LICENSE.GPL3-EXCEPT
/usr/share/doc/qtimageformats/LICENSE.GPLv2
/usr/share/doc/qtimageformats/LICENSE.GPLv3
/usr/share/doc/qtimageformats/LICENSE.LGPL3
/usr/share/doc/qtimageformats/LICENSE.LGPLv21
/usr/share/doc/qtimageformats/LICENSE.LGPLv3
/usr/share/doc/qtimageformats/src_3rdparty_jasper_COPYRIGHT
/usr/share/doc/qtimageformats/src_3rdparty_jasper_LICENSE
/usr/share/doc/qtimageformats/src_3rdparty_libmng_LICENSE
/usr/share/doc/qtimageformats/src_3rdparty_libmng_qt_LICENSE
/usr/share/doc/qtimageformats/src_3rdparty_libtiff_COPYRIGHT
/usr/share/doc/qtimageformats/src_3rdparty_libwebp_COPYING
